# Generated by Django 6.1.1 on 2026-09-27 10:35

import web.models.user
from django.db import migrations, models


def fix_photo_path(apps, schema_editor):
    """AlterField 只改字段定义，不会动已有行。0001 时期的默认值写成了点号
    'user.photos/default.png'，这里把库里已有的值一并纠正成斜杠。"""
    UserProfile = apps.get_model('web', 'UserProfile')
    UserProfile.objects.filter(photo='user.photos/default.png').update(photo='user/photos/default.png')


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='user/photos/default.png', upload_to=web.models.user.photo_upload_to),
        ),
        migrations.RunPython(fix_photo_path, migrations.RunPython.noop),
    ]
